name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  setup:
    name: setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: install dpendencies
        run: npm ci --ignore-scripts

  build:
    name: build
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: restore node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: check build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: my_site
          path: dist
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
          
  deploy:
    runs-on: ubuntu-latest 
    needs: action
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
