name: Pretter

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: install dpendencies
        run: npm ci --ignore-scripts
  lint:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: restore node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Run Prettier
        run: npm run fix:js
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: 🥺Pritty